platform :ios, '12.0'
use_frameworks! :linkage => :static
use_modular_headers!

install! 'cocoapods', :deterministic_uuids => false

require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

